version: "3.5"

services:
  frontend:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/home/evgenii/PycharmProjects/planner-AI-copy/docker
    networks:
      - local-planner-network
    env_file:
      - .env

networks:
  local-planner-network:
    driver: bridge
