# Generated by Django 4.1.3 on 2023-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="tokens_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="chat",
            name="counter",
            field=models.IntegerField(default=0),
        ),
    ]
