# Generated by Django 4.1.3 on 2023-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0002_chat_tokens_used_alter_chat_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_conversation",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="chat",
            name="username",
            field=models.CharField(default="", max_length=300),
        ),
    ]
