# Generated by Django 4.1.3 on 2023-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0003_chat_last_conversation_chat_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="current_mode",
            field=models.CharField(default="chatGPT", max_length=300),
        ),
    ]
