# Generated by Django 4.1.3 on 2023-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0006_chat_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="expenses",
            field=models.FloatField(default=0),
        ),
    ]
