# Generated by Django 4.1.3 on 2023-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="language",
            field=models.CharField(
                choices=[("russian", "russian"), ("english", "english")],
                default="english",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("parents", "parents"),
                    ("user", "user"),
                    ("none", "none"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
