# Generated by Django 4.1.3 on 2023-03-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_q", "0014_schedule_cluster"),
        ("tg_bot", "0003_chat_last_conversation_chat_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.TextField()),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tg_bot.chat"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_q.schedule",
                    ),
                ),
            ],
        ),
    ]
